#!/usr/bin/env python3

import sys

def factorize_number(number):
    factors = []
    divisor = 2
    while divisor <= number:
        if number % divisor == 0:
            factors.append(divisor)
            number //= divisor
        else:
            divisor += 1
    return factors

def factorize_file(filename):
    with open(filename, 'r') as file:
        for line in file:
            number = int(line.strip())
            factors = factorize_number(number)
            factorization = ""
            for i in range(len(factors) - 1):
                factorization += str(factors[i]) + "*"
            factorization += str(factors[-1])
            print(f"{number}={factorization}")

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    filename = sys.argv[1]
    factorize_file(filename)
