#!/usr/bin/env python3

import sys
import math
import random

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def pollards_rho_factorize(number):
    if number == 2:
        return [2]

    if number % 2 == 0:
        return [2] + pollards_rho_factorize(number // 2)

    x = random.randint(1, number - 1)
    c = random.randint(1, number - 1)
    y = x
    d = 1

    while d == 1:
        x = (x**2 + c) % number
        y = (y**2 + c) % number
        y = (y**2 + c) % number
        d = gcd(abs(x - y), number)

    if d == number:
        return pollards_rho_factorize(number)
    
    return [d] + pollards_rho_factorize(number // d)

def factorize_number(number):
    factors = pollards_rho_factorize(number)
    return factors

def factorize_file(filename):
    with open(filename, 'r') as file:
        for line in file:
            number = int(line.strip())
            factors = factorize_number(number)
            factorization = '*'.join(map(str, factors))
            print(f"{number}={factorization}")
            sys.stdout.flush()  # Flush the output to ensure it's printed immediately

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    filename = sys.argv[1]
    factorize_file(filename)

